package com.back.report.model.enums;

public enum ReportReasonType {
    SHOPPING,
    COUNTERFEIT,
    VIOLENCE_ABUSE_EXPLOITATION,
    HATE_HARASSMENT,
    SUICIDE_SELF_HARM,
    BODY_IMAGE_EATING,
    DANGEROUS_ACTIVITIES,
    NUDITY_SEXUAL_CONTENT,
    SHOCKING_GRAPHIC,
    MISINFORMATION,
    SCAM_SPAM,
    REGULATED_GOODS
}
