package com.back.report.model.enums;

public enum ReportReasonType {
    BODY_IMAGE_EATING,
    COUNTERFEIT,
    DANGEROUS_ACTIVITIES,
    HATE_HARASSMENT,
    MISINFORMATION,
    NUDITY_SEXUAL_CONTENT,
    REGULATED_GOODS,
    SCAM_SPAM,
    SHOCKING_GRAPHIC,
    SHOPPING,
    SUICIDE_SELF_HARM,
    VIOLENCE_ABUSE_EXPLOITATION
}